# https://travis-ci.org/dj-stripe/dj-stripe/
dist: trusty
sudo: false
language: python

python: "3.6"

addons:
  postgresql: "9.6"

env:
  - TOXENV=py27-django111
  - TOXENV=py34-django111
  - TOXENV=py34-django20
  - TOXENV=py35-django111
  - TOXENV=py35-django20
  - TOXENV=py35-djangomaster
  - TOXENV=py36-django111
  - TOXENV=py36-django20
  - TOXENV=py36-djangomaster
  - TOXENV=checkmigrations
  - TOXENV=flake8

matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=py35-django111
    - python: "3.5"
      env: TOXENV=py35-django20
    - python: "3.5"
      env: TOXENV=py35-djangomaster
  exclude:
    - python: "3.6"
      env: TOXENV=py35-django111
    - python: "3.6"
      env: TOXENV=py35-django20
    - python: "3.6"
      env: TOXENV=py35-djangomaster
  allow_failures:
    - env: TOXENV=py35-djangomaster
    - env: TOXENV=py36-djangomaster

install:
  - pip install --upgrade pip setuptools wheel
  - pip install tox codecov

before_script:
  - psql -U postgres -c 'CREATE DATABASE "djstripe";'

script:
  - tox

after_success:
  - codecov

notifications:
  email:
    on_failure: always
    on_success: change
