# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

env:
  - DJANGO=1.4
  - DJANGO=1.5

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
    - pip install -r requirements_test.txt

# command to run tests, e.g. python setup.py test
script: python runtest