# https://travis-ci.org/dj-stripe/dj-stripe/
dist: xenial
language: python

cache: pip

addons:
  postgresql: "10"

matrix:
  fast_finish: true

  include:
    - { python: "3.5", env: TOXENV=py35-django21 }
    - { python: "3.5", env: TOXENV=py35-django22 }
    - { python: "3.6", env: TOXENV=py36-django21 }
    - { python: "3.6", env: TOXENV=py36-django22 }
    - { python: "3.7", env: TOXENV=py37-django21 }
    - { python: "3.7", env: TOXENV=py37-django22 }
    - { python: "3.7", env: TOXENV=py37-djangomaster }
    - { python: "3.7", env: TOXENV=checkmigrations }
    - { python: "3.7", env: TOXENV=flake8 }
    - { python: "3.7", env: TOXENV=docs }
  allow_failures:
    - env: TOXENV=py37-djangomaster

install:
  - pip install --upgrade pip setuptools wheel
  - pip install tox codecov

before_script:
  - psql -U postgres -c 'CREATE DATABASE "djstripe";'

script:
  - tox

after_success:
  - codecov
